### ISSUE TITLE
feature toggle pom.properties checking

### ISSUE THREAD

**Issue by arnaldo82** [bsorrentino/maven-bulk-deploy#2]
It should be handy to have the possibility to configure if check or not for pom.properties inside maven artifacts. Some legacy projects could require to impose from external maven coordinates overriding the standard ones present in pom.properties inside the jar.

I propose to add a new not mandatory parameter _ignorePomProperties_ for _DeployFolderMojo_ with default = false

**Comment by bsorrentino** [comment]
Hi @arnaldo82 

I've implemented requested feature in version `2.0-SNAPSHOT`.

Please test it and let me know if works as expected.

### set repository to work with snapshot
```xml
<pluginRepositories>

    <!-- IF YOU WANT STAY TUNED ON UPDATE REMOVE COMMENT -->
    <pluginRepository>
        <id>sonatype-repo</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>

</pluginRepositories>

```

**Comment by arnaldo82** [comment]
Thanks Bartolo,
I did the implementation as well of also the others issues, but i would like to submit it to you because except for this the others are little bit custom requests. I will test it in the mean time, i can provide a pull request for my implementation and we can merge the 2 if you approve the other issues. I will do the pull and then we can choose how to proceed. Thanks a lot

**Comment by bsorrentino** [comment]
Hi @arnaldo82 please proceed ... 

> keep in mind that I've done a refactoring to move implementation on **Java 8** and **Maven 3.5** and have pushed it in `develop` branch

**Comment by arnaldo82** [comment]
It works fine...can i submit a pull request on develop with the other issues open by me? Thanks

**Comment by bsorrentino** [comment]
@arnaldo82 please proceed

**Comment by arnaldo82** [comment]
@bsorrentino this can be closed...it's already merged
