### ISSUE TITLE
Grab all source folder jars without specify them one by one inside _includes_ array

### ISSUE THREAD

**Issue by arnaldo82** [bsorrentino/maven-bulk-deploy#3]
It could be handy to add all jars present in sourceFolder with a wildchar like * without specifying their names through the array parameter includes

**Comment by bsorrentino** [comment]
the `includes` parameter is the solution

### example
```xml
      <includes>
        <include>*.jar</include>
      </includes>
```

**Comment by arnaldo82** [comment]
wonderful! I missed this usage!

**Comment by arnaldo82** [comment]
I think my misunderstanding was that 's is both 3 singular person of the verb and plural of the name :)
