### ISSUE TITLE
Provide an alternative to filePattern regex to desume maven artifact coordinates from file name

### ISSUE THREAD

**Issue by arnaldo82** [bsorrentino/maven-bulk-deploy#4]
For not maven standard artifacts a new not mandatory parameter like _useSameGroupIdAsArtifactId_ could be useful to avoid the awkwardness of regex groups matching
artifactId and GroupId.

A thumb rule could be:

-  take all filename content after the last _-_  and before file extension and manage it as a **fallback** to version parameter. 
- all content before the last _-_ or before _.jar_  identify both artifactId and GroupId.

Example:

guava-19.0.jar

If _version_ not set and _useSameGroupIdAsArtifactId_ = true

groupId: guava
artifactId: guava
version: 19.0

if _version_ set to xxx and _useSameGroupIdAsArtifactId_ = true
groupId: guava-19.0
artifactId: guava-19.0
version: xxx

**Comment by arnaldo82** [comment]
Hi Bartolo,
could you give me rights to push a branch and pull request on develop?

Many thanks,
Hugs,
Arnaldo

**Comment by bsorrentino** [comment]
Hi @arnaldo82 

I don't understand what you are asking  .... please follow [the standard PR process ](https://help.github.com/en/articles/creating-a-pull-request)

**Comment by arnaldo82** [comment]
Hi @bsorrentino 
I got a 403 when trying to push on remote branch. Should I fork the repo as suggested ny doc you linked?

![image](https://user-images.githubusercontent.com/1714168/59362771-5081a400-8d34-11e9-9f83-083250b69a18.png)

**Comment by bsorrentino** [comment]
Hi @arnaldo82 

I've seen that you haven't created your [personal fork](https://help.github.com/en/articles/fork-a-repo)  ... that's the problem

**Comment by bsorrentino** [comment]
fix released in `2.0-rc1`
