### ISSUE TITLE
provide choosing the correct pom.properties in case of fat jar (multiple pom.properties)

### ISSUE THREAD

**Issue by arnaldo82** [bsorrentino/maven-bulk-deploy#6]
Hi @bsorrentino,
I have a standard maven fat jar containing multiple entries for pom.properties (one for each inner dependency plus the correct one).
I.e.
![image](https://user-images.githubusercontent.com/1714168/60671340-2a52ae00-9e73-11e9-85f8-a03e6165da36.png)

_groupId_ parameter of DeployFolderMojo could be used to choose the correct pom.properties in case of fat jar.

If you agree, can I submit a pull request? 

Hugs,

Arnaldo

**Comment by bsorrentino** [comment]
@arnaldo82 seems a interesting feature ... please proceed

**Comment by bsorrentino** [comment]
fix from release `2.0-rc2`
